# Generated by Django 3.2.6 on 2021-08-05 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TaskApp', '0003_auto_20210806_0409'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='text',
        ),
    ]
